services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    environment:
      PORT: 3003
      FRONTEND_URL: http://localhost:4173
      MONGO_URI: mongodb://mongo-rs0-1/test
      SESSION_SECRET: sohgsadighsdiughasdiugdhgishgf
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - 'setup-rs'

  setup-rs:
    build:
      context: .
      dockerfile: Dockerfile.replicaSet
    image: 'setup-rs'
    depends_on:
      - 'mongo-rs0-1'


  mongo-rs0-1:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    image: 'mongo-start'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-rs0-1/data:/data/db


